# Dockerfile for setting up Realsense driver
#  https://github.com/jetsonhacks/installRealSenseSDK
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY realsense/buildLibrealsense.sh /opt/realsense/buildLibrealsense.sh
COPY realsense/installDependencies.sh /opt/realsense/installDependencies.sh

RUN chmod +x /opt/realsense/installDependencies.sh && /opt/realsense/installDependencies.sh
RUN chmod +x /opt/realsense/buildLibrealsense.sh && /opt/realsense/buildLibrealsense.sh