# Dockerfile for setting up Realsense driver
#  https://github.com/jetsonhacks/installRealSenseSDK
ARG BASE_IMAGE
FROM ${BASE_IMAGE}


RUN add-apt-repository ppa:ubuntu-toolchain-r/test && \
    apt-get update && \
    apt-get install -y gcc-11 \
      g++-11 \
      libgstreamer1.0-dev \
      libgstreamer-plugins-base1.0-dev \
      libusb-1.0-0-dev\
      udev

# Copy custom udev rules file
COPY udev_rules/80-movidius.rules /etc/udev/rules.d/80-movidius.rules
